# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Encoder_interface/Encoder_interface.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Encoder_interface || ORIG_REF_NAME==Encoder_interface} -quiet] -quiet

# IP: bd/Encoder_interface/ip/Encoder_interface_encoder_0_0/Encoder_interface_encoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Encoder_interface_encoder_0_0 || ORIG_REF_NAME==Encoder_interface_encoder_0_0} -quiet] -quiet

# XDC: d:/work_directory/TDC/Encoder_vivado/Encoder/Encoder.gen/sources_1/bd/Encoder_interface/Encoder_interface_ooc.xdc
