# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/work_directory/TDC/Channel/Channel/Channel.srcs/sources_1/bd/Channel/ip/Channel_Pipe_0_0/Channel_Pipe_0_0.xci
# IP: The module: 'Channel_Pipe_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/work_directory/TDC/Channel/Channel/Channel.gen/sources_1/bd/Channel/ip/Channel_Pipe_0_0/src/fifo_generator_0/fifo_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: d:/work_directory/TDC/Channel/Channel/Channel.gen/sources_1/bd/Channel/ip/Channel_Pipe_0_0/src/fifo_generator_0/fifo_generator_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: d:/work_directory/TDC/Channel/Channel/Channel.srcs/sources_1/bd/Channel/ip/Channel_Pipe_0_0/Channel_Pipe_0_0.xci
# IP: The module: 'Channel_Pipe_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/work_directory/TDC/Channel/Channel/Channel.gen/sources_1/bd/Channel/ip/Channel_Pipe_0_0/src/fifo_generator_0/fifo_generator_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: d:/work_directory/TDC/Channel/Channel/Channel.gen/sources_1/bd/Channel/ip/Channel_Pipe_0_0/src/fifo_generator_0/fifo_generator_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
