# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Channel/Channel.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Channel || ORIG_REF_NAME==Channel} -quiet] -quiet

# IP: bd/Channel/ip/Channel_Main_Counter_0_0/Channel_Main_Counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Channel_Main_Counter_0_0 || ORIG_REF_NAME==Channel_Main_Counter_0_0} -quiet] -quiet

# IP: bd/Channel/ip/Channel_Encoder_0_0/Channel_Encoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Channel_Encoder_0_0 || ORIG_REF_NAME==Channel_Encoder_0_0} -quiet] -quiet

# IP: bd/Channel/ip/Channel_Eliminator_0_0/Channel_Eliminator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Channel_Eliminator_0_0 || ORIG_REF_NAME==Channel_Eliminator_0_0} -quiet] -quiet

# IP: bd/Channel/ip/Channel_Pipe_0_0/Channel_Pipe_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Channel_Pipe_0_0 || ORIG_REF_NAME==Channel_Pipe_0_0} -quiet] -quiet

# XDC: d:/work_directory/TDC/Channel/Channel/Channel.gen/sources_1/bd/Channel/Channel_ooc.xdc
